image: maven:3.9.6-eclipse-temurin-21

stages:
  - code_quality
  - test
  - release
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  AZURE_WEBAPP_NAME: "mon-serveur"
  AZURE_RESOURCE_GROUP: "mon-groupe"
  AZURE_SUBSCRIPTION_ID: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

cache:
  key: maven-cache
  paths:
    - .m2/repository

# Analyse les potentielles erreurs de logique (manipulation incorrecte des objets, erreur d'injection)
spotbug:
  stage: code_quality
  script:
    - mvn spotbugs:check
  only:
    - merge_requests
  artifacts:
    when: always
    paths:
      - target/spotbugs-report.html

# Analyse statique du code, assure le formattage, les conventions de nommage et la documentation
checkstyle:
  stage: code_quality
  script:
    - mvn checkstyle:check
  only:
    - merge_requests
  artifacts:
    when: always
    paths:
      - target/checkstyle-result.xml

# Analyse des dépendances pour trouver des vulnérabilités communes
dependency-check:
  stage: code_quality
  script:
    - mvn dependency-check:aggregate
  only:
    - merge_requests
  artifacts:
    when: always
    paths:
      - target/dependency-check-report.html

# 📌 2. Exécution des tests
# test:
#   stage: test
#   script:
#     - mvn test
#   artifacts:
#     paths:
#       - target/surefire-reports  # Stocke les rapports de test
#     expire_in: 7 days

# # 📌 3. Préparation de la release (sur merge vers master)
# release:
#   stage: release
#   script:
#     - mvn release:prepare release:perform -B
#   only:
#     - master  # Ne s'exécute que sur la branche master
#   artifacts:
#     paths:
#       - target/*.jar
#     expire_in: 1 month

# # 📌 4. Déploiement sur Azure App Service (sur master)
# deploy:
#   stage: deploy
#   image: mcr.microsoft.com/azure-cli  # Image officielle d'Azure CLI
#   script:
#     - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
#     - az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src-path target/*.jar
#   only:
#     - master  # Déploiement uniquement sur master
